# Model arguments
# could start either from sft or mistral7b
model_name_or_path: HuggingFaceH4/zephyr-7b-beta # alignment-handbook/zephyr-7b-sft-full
torch_dtype: bfloat16
use_flash_attention_2: true
#local_model_name_or_path: alignment-handbook/zephyr-7b-sft-qlora

# LoRA arguments
use_peft: true
load_in_4bit: true
lora_r: 8  # 128
lora_alpha: 32  #128
lora_dropout: 0.1  # 0.05
lora_target_modules:
- q_proj
- k_proj
- v_proj
- o_proj
- gate_proj
- up_proj
- down_proj

# Data training arguments

dataset_mixer:
#  HuggingFaceH4/ultrafeedback_binarized: 1.0
  /projectnb/llamagrp/peter/rlhf_exp/data/uc-30/3p_30d_1r_filtered_self-yl: 1.0

dataset_splits:
-   train_margaret_prefs.json
-   test_margaret_default-other-yl_prefs.json
-   test_margaret_default-yl_prefs.json
-   test_margaret_mixed-yl_prefs.json
-   test_margaret_other-yl_prefs.json
-   test_margaret_self-yl_prefs.json
preprocessing_num_workers: 12
combine_eval_splits: false

# DPOTrainer arguments
bf16: true
beta: 0.01
do_train: true
do_eval: true
evaluation_strategy: steps
eval_steps: 1
gradient_accumulation_steps: 5
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false
hub_model_id: zephyr-7b-dpo-qlora-pp-margaret
learning_rate: 5.0e-6
log_level: info
logging_steps: 1
lr_scheduler_type: cosine
max_length: 1024
max_prompt_length: 512
num_train_epochs: 10
optim: paged_adamw_32bit
output_dir: data/zephyr-7b-dpo-qlora-pp-margaret # It is handy to append `hub_model_revision` to keep track of your local experiments
per_device_train_batch_size: 2 # can go to 4 but loosing end of batch examples from dataset
per_device_eval_batch_size: 10
push_to_hub: false
save_strategy: "steps"
save_steps: 1
save_total_limit: 2
seed: 42
warmup_ratio: 0.1